import React, { useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { StytchLogin, useStytchSession } from '@stytch/nextjs';
import { Products } from '@stytch/vanilla-js';
import { useRouter } from 'next/router';

const STYTCH_LOGO_IMG_URL = 'https://public-assets.stytch.com/stytch_logo_charcoal.png';

const StytchConfig = {
  products: [Products.otp],
  otpOptions: {
    methods: ['email'],
    expirationMinutes: 10,
  },
};

const StyleConfig = {
  logo: {
    logoImageUrl: STYTCH_LOGO_IMG_URL,
  },
};

export default function Login() {
  const router = useRouter();
  const { session, isInitialized } = useStytchSession();

  useEffect(() => {
    if (isInitialized && session !== null) {
      router.push('/profile');
    }
  }, [session, isInitialized, router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Stytch - Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js..!</a>
        </h1>
        <StytchLogin config={StytchConfig} styles={StyleConfig} />
      </main>
    </div>
  );
}
