import React, { useCallback, useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import { useStytch, useStytchSession, useStytchUser } from '@stytch/nextjs';

export default function Profile() {
  const router = useRouter();
  const stytch = useStytch();
  const { session, isInitialized } = useStytchSession();
  const { user } = useStytchUser();

  useEffect(() => {
    if (isInitialized && session === null) {
      router.push('/login');
    }
  }, [session, isInitialized, router]);

  const logout = useCallback(async () => {
    stytch.session.revoke().finally(() => router.push('/login'));
  }, [router, stytch.session]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Stytch - Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>User</h1>
        <pre>{JSON.stringify(user, null, 2)}</pre>
        <br />
        <h1>Session</h1>
        <pre>{JSON.stringify(session, null, 2)}</pre>
        <br />
        <button onClick={logout}>Log Out</button>
      </main>
    </div>
  );
}
