export enum Screen {
  Main = 'Main',
  EmailConfirmation = 'EmailConfirmation',
  Success = 'Success',
  Discovery = 'Discovery',
  Error = 'Error',
  PasswordAuthenticate = 'PasswordAuthenticate',
  PasswordResetForm = 'PasswordResetForm',
  PasswordResetVerifyConfirmation = 'PasswordResetVerifyConfirmation',
  PasswordForgotForm = 'PasswordForgotForm',
  PasswordSetNew = 'PasswordSetNew',
  PasswordSetNewConfirmation = 'PasswordSetNewConfirmation',
  MFAEnrollmentSelection = 'MFAEnrollmentSelection',
  RecoveryCodeEntry = 'RecoveryCodeEntry',
  RecoveryCodeSave = 'RecoveryCodeSave',
  SMSOTPEnrollment = 'SMSOTPEnrollment',
  SMSOTPEntry = 'SMSOTPEntry',
  TOTPEnrollmentManual = 'TOTPEnrollmentManual',
  TOTPEntry = 'TOTPEntry',
  EmailOTPEntry = 'EmailOTPEntry',
  EmailMethodSelection = 'EmailMethodSelection',
  SSODiscoveryEmail = 'SSO Discovery Email',
  SSODiscoveryFallback = 'SSO Discovery Fallback',
  SSODiscoveryMenu = 'SSO Discovery Menu',
}
