blank_issues_enabled: true
contact_links:
  - name: Support / Bug reports
    url: https://stytch.slack.com/join/shared_invite/zt-3aqo03e10-afWXyLzRIAlzGWJyF_~zHw
    about: Please ask questions and submit bug reports in Slack
