name: deploy-react-demo-app
on:
  workflow_call:
    inputs:
      s3_bucket:
        required: true
        type: string
      sha_to_deploy:
        required: true
        type: string
      env:
        required: true
        type: string
      app_dir:
        required: true
        type: string
      build_script:
        required: true
        type: string
    secrets:
      honeycomb_api_key:
        required: true
      cloudfront_distribution_id:
        required: true
      ci_aws_access_key_id:
        required: true
      ci_aws_secret_access_key:
        required: true
env:
  BUILDEVENT_APIKEY: ${{ secrets.honeycomb_api_key }}
  BUILDEVENT_DATASET: 'stytch-ci'
  BUILDEVENT_CIPROVIDER: 'github-actions'
jobs:
  deploy:
    environment: ${{ inputs.env }}
    name: Deploy Demo App (${{ inputs.app_dir }})
    runs-on: ubuntu-latest
    env:
      S3_BUCKET: ${{ inputs.s3_bucket }}
      APP_DIR: ${{ inputs.app_dir }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha_to_deploy }}

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Choose env file for environment
        env:
          ENV: ${{ inputs.env }}
        run: |
          cp ./apps/$APP_DIR/.env.$ENV ./apps/$APP_DIR/.env
          cat ./apps/$APP_DIR/.env

      - name: Build
        env:
          BUILD_SCRIPT: ${{ inputs.build_script }}
        run: |
          yarn $BUILD_SCRIPT

      - name: Configure AWS credentials from account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ci_aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.ci_aws_secret_access_key }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 sync ./apps/$APP_DIR/dist/ s3://$S3_BUCKET

      - name: Invalidate Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.cloudfront_distribution_id }}
