name: 'Run Canaries'
permissions:
  contents: read
on:
  workflow_dispatch: # Can be called manually
  workflow_call: # Can be called by other workflows
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
jobs:
  # If we add more canaries in the future, they should be top-level jobs like this
  react-native-canary:
    name: Trigger React Native Canary
    permissions:
      contents: read
    uses: ./.github/workflows/react-native-canary.yml
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
